import { ClassInfo } from '@/types/calendarTypes';

export const MOCK_CLASSES: ClassInfo[] = [
    {
        STRM: "2254",
        SUBJECT: "SOEN",
        CATALOG_NBR: "345",
        SSR_COMPONENT: "LEC",
        XLATLONGNAME: "Lecture",
        CLASS_SECTION: "WW",
        DAY_OF_WEEK: "mon",
        START_HOURS: "14",
        START_MINUTES: "45",
        END_HOURS: "16",
        END_MINUTES: "00",
        CU_BLDG: "H",
        CU_BUILDING: "Hall Building",
        ROOM: "535",
        INSTRUCTION_MODE: "E",
        EXPR20_20: "2026-02-06",
        START_DT: "2026-01-12",
        END_DT: "2026-04-13",
        ACAD_CAREER: "UGRD",
        INSTR_NAME: "Hassan Hajjdiab"
    },
    {
        STRM: "2254",
        SUBJECT: "SOEN",
        CATALOG_NBR: "345",
        SSR_COMPONENT: "LEC",
        XLATLONGNAME: "Lecture",
        CLASS_SECTION: "SS",
        DAY_OF_WEEK: "wed",
        START_HOURS: "14",
        START_MINUTES: "45",
        END_HOURS: "16",
        END_MINUTES: "00",
        CU_BLDG: "H",
        CU_BUILDING: "Hall Building",
        ROOM: "535",
        INSTRUCTION_MODE: "E",
        EXPR20_20: "2026-02-06",
        START_DT: "2026-01-12",
        END_DT: "2026-04-13",
        ACAD_CAREER: "UGRD",
        INSTR_NAME: "Hassan Hajjdiab"
    },
    {
        STRM: "2254",
        SUBJECT: "COMP",
        CATALOG_NBR: "445",
        SSR_COMPONENT: "LEC",
        XLATLONGNAME: "Lecture",
        CLASS_SECTION: "W",
        DAY_OF_WEEK: "mon",
        START_HOURS: "13",
        START_MINUTES: "15",
        END_HOURS: "14",
        END_MINUTES: "30",
        CU_BLDG: "FG",
        CU_BUILDING: "Faubourg Building",
        ROOM: "B060",
        INSTRUCTION_MODE: "E",
        EXPR20_20: "2026-02-06",
        START_DT: "2026-01-12",
        END_DT: "2026-04-13",
        ACAD_CAREER: "UGRD",
        INSTR_NAME: "Malleswara Talla"
    },
    {
        STRM: "2254",
        SUBJECT: "COMP",
        CATALOG_NBR: "445",
        SSR_COMPONENT: "LEC",
        XLATLONGNAME: "Lecture",
        CLASS_SECTION: "W",
        DAY_OF_WEEK: "wed",
        START_HOURS: "13",
        START_MINUTES: "15",
        END_HOURS: "14",
        END_MINUTES: "30",
        CU_BLDG: "FG",
        CU_BUILDING: "Faubourg Building",
        ROOM: "B060",
        INSTRUCTION_MODE: "E",
        EXPR20_20: "2026-02-06",
        START_DT: "2026-01-12",
        END_DT: "2026-04-13",
        ACAD_CAREER: "UGRD",
        INSTR_NAME: "Malleswara Talla"
    },
]