import { ClassInfo } from '@/types/calendarTypes';

export const MOCK_CLASSES: ClassInfo[] = [
    {
            strm: "2254",
            subject: "SOEN",
            catalog_nbr: "343",
            ssr_component: "LEC",
            xlatlongname: "Lecture",
            class_section: "WW",
            day_of_week: "thu",
            start_hours: "13",
            start_minutes: "15",
            end_hours: "14",
            end_minutes: "30",
            cu_bldg: "H",
            cu_building: "Hall Building",
            room: "535",
            instruction_mode: "E",
            expr20_20: "2026-02-06",
            start_dt: "2026-01-12",
            end_dt: "2026-04-13",
            acad_career: "UGRD",
            instr_name: "N\\/A"
        },
        {
            strm: "2254",
            subject: "SOEN",
            catalog_nbr: "345",
            ssr_component: "LEC",
            xlatlongname: "Lecture",
            class_section: "UU",
            day_of_week: "wed",
            start_hours: "10",
            start_minutes: "15",
            end_hours: "11",
            end_minutes: "30",
            cu_bldg: "MB",
            cu_building: "John Molson School of Business",
            room: "S2.210",
            instruction_mode: "E",
            expr20_20: "2026-02-05",
            start_dt: "2026-01-12",
            end_dt: "2026-04-13",
            acad_career: "UGRD",
            instr_name: "N\\/A"
        },
        {
            strm: "2254",
            subject: "SOEN",
            catalog_nbr: "345",
            ssr_component: "TUT",
            xlatlongname: "Tutorial",
            class_section: "UUUC",
            day_of_week: "fri",
            start_hours: "08",
            start_minutes: "45",
            end_hours: "09",
            end_minutes: "35",
            cu_bldg: "CL",
            cu_building: "CL Building",
            room: "235",
            instruction_mode: "E",
            expr20_20: "2026-02-07",
            start_dt: "2026-01-12",
            end_dt: "2026-04-13",
            acad_career: "UGRD",
            instr_name: "N\\/A"
        },
]